// DERWriter.swift
// Append-oriented strict-DER builder over an owned [UInt8]. Minimal length
// encoding, sign-safe INTEGER minimization, and BIT STRING unused-bits framing
// — byte-identical to the reference ASN1Builder output. Embedded-clean: no
// Foundation, no `any`.

/// Builds DER by appending primitive TLVs and assembling SEQUENCEs from already
/// encoded child TLVs.
///
/// Length encoding is always minimal (short form < 128, otherwise long form
/// with the fewest octets). INTEGER minimization and BIT STRING framing match
/// the reference `ASN1Builder` exactly, so generated bytes are wire-identical.
public struct DERWriter: Sendable {

    @usableFromInline var storage: [UInt8]

    /// Creates an empty writer.
    @inlinable public init() {
        self.storage = []
    }

    /// Creates a writer with reserved capacity.
    @inlinable public init(reservingCapacity capacity: Int) {
        self.storage = []
        if capacity > 0 {
            self.storage.reserveCapacity(capacity)
        }
    }

    /// The bytes written so far.
    @inlinable public var bytes: [UInt8] { storage }

    /// Consumes the writer and returns the accumulated bytes.
    public consuming func finish() -> [UInt8] { storage }

    // MARK: Minimal length encoding (mirrors ASN1Builder.encodeLength)

    /// Appends the minimal DER length encoding of `length` to `out`.
    @usableFromInline
    static func appendLength(_ length: Int, to out: inout [UInt8]) {
        if length < 128 {
            out.append(UInt8(length))
            return
        }
        // Long form: 0x80 | n, then big-endian length in n minimal octets.
        var lengthBytes = [UInt8]()
        var remaining = length
        while remaining > 0 {
            lengthBytes.insert(UInt8(remaining & 0xFF), at: 0)
            remaining >>= 8
        }
        out.append(UInt8(0x80 | lengthBytes.count))
        out.append(contentsOf: lengthBytes)
    }

    // MARK: Primitive TLV writers

    /// Appends `tag ++ len(content) ++ content`.
    public mutating func appendTLV(_ tag: DERTag, content: [UInt8]) {
        storage.append(tag.rawValue)
        Self.appendLength(content.count, to: &storage)
        storage.append(contentsOf: content)
    }

    /// Appends an OBJECT IDENTIFIER (`0x06 ++ len ++ oid.der`).
    public mutating func appendOID(_ oid: ObjectID) {
        appendTLV(.objectIdentifier, content: oid.der)
    }

    /// Appends an INTEGER with sign-safe minimization (identical to
    /// `ASN1Builder.integer`): prepend `0x00` iff the high bit of the first
    /// content byte is set, then strip leading `0x00` while the next byte's
    /// high bit is clear.
    public mutating func appendInteger(_ bytes: [UInt8]) {
        var value = bytes
        if value.isEmpty {
            // An empty input encodes as a single zero octet (DER INTEGER 0).
            value = [0x00]
        }
        if let first = value.first, first & 0x80 != 0 {
            value.insert(0x00, at: 0)
        }
        while value.count > 1 && value[0] == 0x00 && (value[1] & 0x80) == 0 {
            value.removeFirst()
        }
        appendTLV(.integer, content: value)
    }

    /// Appends a BIT STRING, prepending a single `0x00` unused-bits octet
    /// (identical to `ASN1Builder.bitString(_, unusedBits: 0)`).
    public mutating func appendBitString(_ bytes: [UInt8]) {
        var content = [UInt8]()
        content.reserveCapacity(bytes.count + 1)
        content.append(0x00)
        content.append(contentsOf: bytes)
        appendTLV(.bitString, content: content)
    }

    /// Appends an OCTET STRING.
    public mutating func appendOctetString(_ bytes: [UInt8]) {
        appendTLV(.octetString, content: bytes)
    }

    /// Appends a BOOLEAN (DER true == 0xFF, false == 0x00).
    public mutating func appendBoolean(_ value: Bool) {
        appendTLV(.boolean, content: [value ? 0xFF : 0x00])
    }

    /// Appends a UTCTime (`0x17`, `"yyMMddHHmmssZ"`). Matches the reference
    /// builder which always emits UTCTime for the M6a validity range.
    public mutating func appendUTCTime(epochSeconds: Int64) {
        appendTLV(.utcTime, content: DERTime.utcTimeBytes(epochSeconds: epochSeconds))
    }

    /// Appends a GeneralizedTime (`0x18`, `"yyyyMMddHHmmssZ"`). Forward-safety
    /// for years >= 2050; not on the libp2p critical path.
    public mutating func appendGeneralizedTime(epochSeconds: Int64) {
        appendTLV(.generalizedTime, content: DERTime.generalizedTimeBytes(epochSeconds: epochSeconds))
    }

    /// Appends an EXPLICIT context-tagged value (`[0]`/`[3]`): `tag ++ len ++ content`.
    public mutating func appendContextExplicit(_ tag: DERTag, content: [UInt8]) {
        appendTLV(tag, content: content)
    }

    /// Appends already-encoded child TLVs wrapped in a SEQUENCE.
    public mutating func appendSequence(_ children: [[UInt8]]) {
        storage.append(contentsOf: Self.sequence(children))
    }

    // MARK: Static helpers (compose without an instance)

    /// Wraps already-encoded child TLVs in a SEQUENCE: `0x30 ++ len(Σ) ++ Σchildren`.
    public static func sequence(_ children: [[UInt8]]) -> [UInt8] {
        var content = [UInt8]()
        for child in children {
            content.append(contentsOf: child)
        }
        return encode(.sequence, content)
    }

    /// Encodes a single primitive/constructed TLV: `tag ++ len(content) ++ content`.
    public static func encode(_ tag: DERTag, _ content: [UInt8]) -> [UInt8] {
        var out = [UInt8]()
        out.append(tag.rawValue)
        appendLength(content.count, to: &out)
        out.append(contentsOf: content)
        return out
    }

    /// Encodes an OBJECT IDENTIFIER TLV from its content octets.
    public static func encodeOID(_ oid: ObjectID) -> [UInt8] {
        encode(.objectIdentifier, oid.der)
    }

    /// Encodes a BOOLEAN TLV.
    public static func encodeBoolean(_ value: Bool) -> [UInt8] {
        encode(.boolean, [value ? 0xFF : 0x00])
    }

    /// Encodes an OCTET STRING TLV.
    public static func encodeOctetString(_ bytes: [UInt8]) -> [UInt8] {
        encode(.octetString, bytes)
    }

    /// Encodes a BIT STRING TLV (single `0x00` unused-bits octet).
    public static func encodeBitString(_ bytes: [UInt8]) -> [UInt8] {
        var content = [UInt8]()
        content.reserveCapacity(bytes.count + 1)
        content.append(0x00)
        content.append(contentsOf: bytes)
        return encode(.bitString, content)
    }

    /// Encodes an INTEGER TLV with sign-safe minimization.
    public static func encodeInteger(_ bytes: [UInt8]) -> [UInt8] {
        var w = DERWriter()
        w.appendInteger(bytes)
        return w.finish()
    }
}
